server:
  port: 8080
  servlet:
    context-path: /rm
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resource_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 111111
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: org.dawn.rm.db.model
  configuration:
    map-underscore-to-camel-case: true